Repository the-vision/jarvis-core, pull requests merged in 2020-05, with the labels that each got.

#79 More dictionary training data added
  data/nlu.md
  test.py
Labels: bug, easy, gssoc20

#82 Added new intent: memes
  data/nlu.md
  test.py
Labels: easy, gssoc20

#51 Add ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
Labels: beginner, gssoc20

#52 Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: beginner, gssoc20

#80 Added new intent: anime
  data/nlu.md
  test.py
Labels: easy, gssoc20

#20 Intent for travel
  data/nlu.md
  test.py
Labels: beginner, gssoc20

#32 Intent: Translator Added
  data/nlu.md
  test.py
Labels: beginner, gssoc20

#37 Update nlu.md
  data/nlu.md
  test.py
Labels: beginner, gssoc20

#70 Add new intents TIME and CONVERT TIME
  data/nlu.md
  test.py
Labels: easy, gssoc20

#64 Added new intent: currency
  data/nlu.md
  test.py
Labels: easy, gssoc20

#84 Added new intent: video
  data/nlu.md
  test.py
Labels: easy, gssoc20

#78 Cricket score
  data/nlu.md
  test.py
Labels: beginner, gssoc20
